Repository codit-FE-17-part4-team1/globalnomad, pull requests merged in 2025-10, with the labels that each got.

#15 feat: common-header 추가
  .storybook/main.ts
  src/app/test-header/page.tsx
  src/components/.gitkeep
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.tsx
  src/components/Header/NotificationButton.tsx
  src/components/Header/Profile.tsx
  src/components/Header/TestHeader.tsx
  src/components/Header/UserMenu.tsx
  src/components/ProfileImage/ProfileImage.tsx
  src/hooks/.gitkeep
  src/utils/.gitkeep
Labels: 기능

#17 feat: common-footer 추가
  src/app/test-footer/page.tsx
  src/components/Footer/Footer.stories.tsx
  src/components/Footer/Footer.tsx
  src/components/Footer/TestFooter.tsx
Labels: 기능

#19 feature:common-datePicker 추가
  src/components/datepicker/DatePicker.stories.tsx
  src/components/datepicker/DatePicker.tsx
  src/components/datepicker/TestDatePicker.tsx
  src/components/datepicker/datePicker.css
Labels: 기능

#22 feat: feature/common-dropdown 추가
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonTest.tsx
  src/components/ButtonTest.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownTest.tsx
Labels: 기능

#23 feat: MyInfo페이지 UI추가, Profile 공통 컴포넌트 추가
  src/app/Profile/MyInfo/page.tsx
  src/app/Profile/_components/MypageHeader/MypageHeader.tsx
  src/app/Profile/_components/MypageHeader/TestMypageHeader.tsx
  src/app/Profile/_components/Nodata/Nodata.tsx
  src/app/Profile/info/page.tsx
  src/components/chips/TestChips.tsx
  src/components/datepicker/DatePicker.tsx
Labels: UI

#27 feat: 메인(home) 페이지 신규 추가
  package-lock.json
  public/icon/btn/alt_arrow_left.svg
  public/icon/btn/alt_arrow_right.svg
  public/icon/favicon.png
  public/images/card_cover.svg
  public/images/og-image.png
  src/app/_components/main/AllExperiences.tsx
  src/app/_components/main/CategoryButtons.tsx
  src/app/_components/main/ExperiencesCard.stories.tsx
  src/app/_components/main/ExperiencesCard.tsx
  src/app/_components/main/MainBanner.tsx
  src/app/_components/main/Pagination.tsx
  src/app/_components/main/PopularExperiences.tsx
  src/app/_components/main/PriceFilter.tsx
  src/app/_components/main/RecentSearchList.tsx
  src/app/_components/main/SearchBar.tsx
  src/app/head.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/ButtonTest.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
Labels: 기능, UI

#33 feat:ReservationHistory페이지, 리뷰모달 추가
  public/icon/confirm_check.svg
  src/app/Profile/MyInfo/page.tsx
  src/app/Profile/ReservationHistory/_components/Modal/CancelModal.tsx.tsx
  src/app/Profile/ReservationHistory/_components/Modal/ReviewModal.tsx
  src/app/Profile/ReservationHistory/_components/StarButton.tsx
  src/app/Profile/ReservationHistory/mockData.ts
  src/app/Profile/ReservationHistory/page.tsx
  src/app/Profile/_components/MypageHeader/MypageHeader.tsx
Labels: UI

#30 feat: 초기페이지, 로그인/회원가입 페이지
  public/icon/social/kakao.svg
  src/app/Login/page.stories.tsx
  src/app/Login/page.tsx
  src/app/Signup/page.stories.tsx
  src/app/Signup/page.tsx
  src/components/Input/FormInput.tsx
Labels: UI
